{% set xorg_name = "libXext" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.3.3" %}
{% set sha256 = "b518d4d332231f313371fdefac59e3776f4f0823bcb23cf7c7305bfb57b16e35" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - m2w64-pkg-config  # [win]
    - pthread-stubs
    - xorg-kbproto
    - xorg-libx11 1.6.*
    - xorg-util-macros
    - xorg-xextproto
    - xorg-xproto
  run:
    - xorg-libx11 1.6.*
    - xorg-xextproto

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'The X.org extensions library.'

extra:
  recipe-maintainers:
    - pkgw
