travis:
  secure:
    BINSTAR_TOKEN: jNe4B2QdOfe1WFnYKE8AHpkzZrbILYoIJqeD6+Mds3BCUnkVpS43Mo235yKCuWiWGdNF76Oqql2/MRhXexcb9X6uFM/MYfUWg5wOrlAFRW6YF4aE8V05EK95E3XPt9NDnKp4wLOMdVvxAZFR2w2TQAx74vGMde/8lA5e+U/oROQckzUJyzoFqj25va8sDFSSmIrs8G4jr/YpJH7P9ls2/L37t5mdBg3uvKLGSZ4b8lD6WKxO4jke9xPlzDGtc74lQ8vn+9FiK7Ut/utSqvCnZwedFgSTxcFHdTSFm0rQo6Ri36wIUEN8JTXm2ysnX3htHs1EDez+XWDYp/YDN36smxUGdSiW8gK5x6UITaDRvcwx63FIrEy7J0c4Oj89F9VnbEV9x8gj9izGo+9ggvzDlcL4jOWOFkBze2XXxRrc1ZIxTHdgVJ/1K5i4vfjNxGAIHM8ePiE8CJTUNYc9OBperEiSH58JZuLeoo5HjCgLmd/DGAn8XylRSYu1Rs37iS+o3BxfYaBeV2nD7nonWFdTdg4hKmn71XJEp9EAPL6EaEF1Gqs2JIHUJLI21DCAwquHm1+iIeSWPQtJbkGfdexF6YOjPyPGwMQ8wiHLTHgk6bQx/svTSfagLUqBvza4P+z/+XhSbssBAR90vbkydCJy42Pd4Y8A5khFNcx68o9ooCQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
