travis:
  secure:
    BINSTAR_TOKEN: d7cLZJvCRGBvqlx/WUaDMLc+9YrLuFuRtGCDzw/ErzSnPjlVhNjcWVHBRueV/YUg9vvDSingOz0dkySWRkG8yjzKnTmvH6xSBQJXNXT8yk+S8aqt5ZlnEvKArS90hinidXzwqXpHNTlbgNro+HJs/jsaENd/IHypp1L5ndC5vcPvvxAz4tK9FQCRpiW82YJTI/ZDJzONb1oLp7cp5JBV5sHwrT7npKIBTPn4IDfvWG4rJdkgct4wAMbTP7xq0OD3FZNN8uhh+eHEMIVwVoUBukk+f0++QCdSTxbRUCuEtKsCrdCE3zFNQKa8wejsO+/0VKDmEH/CLRsTBoLQgWDWZhdNZwoZDgg3id6kT+kIfIcpfIduyypWU7+JzOak1E+5jaXlniM8kKd0VNhJt4a1M6LTlAArylRntRtTvR11mgn3f4GzUYvqvxNQGNmQTtMgzziu5MzHATt8toXGcaeeEMxHLW34n+VMwAJdki8Gz1MmVO+2LQX9CR1J9RYN1tIndycLz4BIEO9HopxGXg3rnW1cRwNaqIzw5kISLebtREmIHdskS4r60nCNmzZCqMzfOFjyfHVNLdcDLVNKHtQZJd8kaca/jvqR7qdchyjII03EcIwj+erjO1ZeJ4iLXhlozn21fL1avkZIqhhwgFc5boBJAdKyP90OHWW4Nl/r+F8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
